name: CI/CD Pipeline

# Тригери: події, які запускають пайплайн
on:
  push:
    [cite_start]branches: [ main, develop ] # Запуск при кожному пуші в ці гілки 
  pull_request:
    [cite_start]branches: [ main, develop ] # Запуск при створенні Pull Request [cite: 431-435]

jobs:
  build-and-test:
    name: Build and Test
    [cite_start]runs-on: ubuntu-latest # Віртуальна машина, на якій все працює 

    steps:
      - name: Checkout repository
        [cite_start]uses: actions/checkout@v4 # Крок для отримання коду з твого репозиторію